<template>
         <n-checkbox class="noprint" v-model:checked="displayADirectly" @update:checked="handledisplayADirectlyCheckedChange">
          直接从组卷网获取答案解析数据而非从oss缓存
        </n-checkbox>
        <n-button @click="OCRAll(8)" class="noprint">OCR all chars</n-button> 
        <n-button @click="OCRAll(3)" class="noprint">OCR all blocks</n-button> 
    <div :style="{width:'18.76cm','line-height':'normal'}" id="oonom">
        <div class="noprint">
            <!-- <div class="labi-container">
                <div class="labi-block" v-for="rr in [1,2,3,4,5,6,7]" :key="rr" 
        :style="{height:1045+'px'}">Page # {{rr}}</div>
        </div> -->
        </div>      <n-image-group> 
        <div id="corehtml" :style="{width:'18.76cm',columns:2,'line-height':'normal'}">
        <p style="font-size:9.5pt;font-family:Cambria , fangsong;margin:0px">Generated by thost | Group UUID: {{$route.params.id}} | Title: {{grouptitle}}</p>
    <div v-for="oo in chunk2array(Tlist)" :key="oo.id">
        <p style="font-size:9.5pt;margin:0px;font-family:Cambria , 仿宋;">UUID:<span style="font-family:'courier new'">{{oo.id}}</span> | qid:<span style="font-family:'courier new'">{{oo.qid}}</span> </p>
      <div v-if="displayADirectly">
    
             <n-image  lazy :src="(XKWGetFile[oo.id]||{a:''}).a" v-if="!OCRResAccepted[oo.id]"><template #placeholder><n-spin/></template></n-image>
             <n-button @click="OCRSingle(oo,8)" class="noprint">OCR chars</n-button>   <n-button @click="OCRSingle(oo,3)" class="noprint">OCR block</n-button>  
             <p v-if="orcres[oo.id]" style="margin:0 0;">{{ orcres[oo.id] }}</p>   
             <n-button @click="OCRResAccepted[oo.id]=true"  class="noprint">Accept OCR Result</n-button>
             <div>
        </div></div>
      </div>
    </div>          </n-image-group></div>
    
    </template>
    
    <script setup>
    
    import { onMounted, ref } from "vue"
    import {useRoute,useRouter} from "vue-router"
    const route=useRoute(),router=useRouter()
    
    import {NButton,NCheckbox,NP,NSpin,NImage,NImageGroup} from "naive-ui"
    
    import {normalizeq} from "../../shared/nomorlize_q"
    import {qtypes} from "../../shared/define_basic_qtypes"
    import { API } from "../../shared/APIHelper"
    import swal from "sweetalert"
    const shown=ref({
        q:true,
        a:false,
        p:false
    })
    
    const Noptions_ret2=ref(false)
    const grouptitle=ref("")
    
    const Tlist=ref({})
    let groupentry=[]
    API.post("/api/group/get",{id:route.params.id}).then(sss=>{
    
    sss.entry.split(",").forEach(v => {
        Tlist.value[v]=qtypes
    });
    
    groupentry=sss.entry.split(",")
    
    
    
    grouptitle.value=sss.title
    
    Promise.all(sss.entry.split(",").map(v=>new Promise((res,rej)=>{
    API.get("/api/qapi/get/"+v).then(i=>{
        Tlist.value[v]=i
    })
    GetDoneInfo(v)
    }))).then(()=>{
    
    })
    // fetch("/api/get",{"method":"POST","body":JSON.stringify({id:v}),"headers":{"Content-Type":"application/json"}}).then(o=>o.json()).then(i=>{
    //     Tlist.value[v]=i
    // })
    // }))).then(()=>{
    
    // })
    
    
    
    })
    
    
    
    
    //adddddd
    
    
    const _JSONparse=(v)=>{return JSON.parse(v)}
    
    const doneinfo=ref({})
    
    ,chunk2array=mm=>Object.entries(mm).map(o=>o[1])
    
    
    const markAsDone=async(rel)=>{
        console.log(rel);
        await API.post("/api/qapi/doneinfo/mark",{
    quuid:rel.id,
    timestamp:(new Date()).getTime(),
    displayednote:"",
    note :"",
    rate:50,
    bankid:rel.bankid
    
        })
    }
    
    const markAsDoneAll=async()=>{
            Promise.all(Object.entries(Tlist.value).map(rr=>markAsDone(rr[1]))).then(v=>{
                swal("ok.")
            })
    }
    
    const GetDoneInfo=async(id)=>{
        doneinfo.value[id]= await API.get("/api/qapi/doneinfo/getbyquuid/"+id)
    }
    
    
    const displayADirectly=ref(false),XKWGetFile=ref({})
    const handledisplayADirectlyCheckedChange=(checked)=>{
        console.log(checked);
    displayADirectly.value=checked
    if(displayADirectly.value){
        Object.entries(Tlist.value).forEach(v1 => {
            console.log(v1);
                API.get("/api/xkw-helper/get_more_detail/325/"+v1[1].bankid+"/"+v1[1].qid).then(r=>{
                    
            XKWGetFile.value[v1[1].id]={
                a:API.host+"/api/xkw-helper/route-pic?purl="+btoa(r.data.answerImg.replace("@2","@3").replace("c2","c1")),
                p:API.host+"/api/xkw-helper/route-pic?purl="+btoa(r.data.parseImg.replace("@2","@3").replace("c2","c1")),
            }
    })
        });
    }
    }

const orcres=ref({}),OCRResAccepted=ref({})
    const OCRSingle=(oo,psm)=>{
        API.post("/ocr-service",{
            url:XKWGetFile.value[oo.id].a,
            psm,
            lang:"eng+chi_sim"
        }).then(v=>{
            orcres.value[oo.id]=v.result
        })
    }
    const OCRAll=(psm)=>{
        for (let i = 0; i < chunk2array(Tlist.value).length; i++) {
            let oo=chunk2array(Tlist.value)[i]

            console.log(oo);
            API.post("/ocr-service",{
            url:XKWGetFile.value[oo.id].a,
            psm,
            lang:"eng+chi_sim"
        }).then(v=>{
            orcres.value[oo.id]=v.result
        })
        }

    }
    </script>
    
    <style>
    @media print{
        .noprint{
            display: none;
        }
    
    }
    
    .noprint{
            user-select: none;
        }
    /* .labi-container{
        display: block;
        height: fit-content;
        width: 100%;
        position: absolute;
        z-index: -1;
    }
    .labi-block{
        display: block;
        width: 100%;
        border-bottom-color: black;
        border-bottom-width: 2px;
        position:relative;
        border-bottom-style: dotted;
        text-align:right;
    } */
    
    img{
        max-width: 350px;
    }
    
    td{
        padding:0
    }
    </style>
    