<template>
<n-button class="noprint" @click="shown.q=!shown.q">Q</n-button>
<n-button class="noprint" @click="shown.a=!shown.a">A</n-button>
<n-button class="noprint" @click="shown.p=!shown.p">P</n-button>
<n-button @click="router.push('/grouping/preexport-1/'+route.params.id)">开始准备打印</n-button>
<n-button @click="router.push('/grouping/preexport-1/'+route.params.id+'/word_tailored_version')">开始准备优化并嵌入Word</n-button>
<n-button @click="router.push('/export/'+route.params.id+'/a')">打印答案</n-button>
<n-button @click="markAsDoneAll">将本group内所有试题标记为done</n-button>
    <n-checkbox v-model:checked="displayADirectly" @update:checked="handledisplayADirectlyCheckedChange">
      直接从组卷网获取答案解析数据而非从oss缓存
    </n-checkbox>
<div :style="{width:'18.76cm','line-height':'normal'}" id="oonom">
    <div class="noprint">
        <!-- <div class="labi-container">
            <div class="labi-block" v-for="rr in [1,2,3,4,5,6,7]" :key="rr" 
    :style="{height:1045+'px'}">Page # {{rr}}</div>
    </div> -->
    </div>      <n-image-group> 
    <div id="corehtml" :style="{width:'18.76cm',columns:1,'line-height':'normal'}">
    <p style="font-size:9.5pt;font-family:Cambria , fangsong;margin:0px">Generated by thost | Group UUID: {{$route.params.id}} | Title: {{grouptitle}}</p>
<div v-for="oo in chunk2array(Tlist)" :key="oo.id">
    <p style="font-size:9.5pt;margin:0px;font-family:Cambria , 仿宋;">UUID:<span style="font-family:'courier new'">{{oo.id}}</span> | qid:<span style="font-family:'courier new'">{{oo.qid}}</span> <span v-if="shown.q">| Info: {{_JSONparse(oo.extra).info}} | Origin: {{_JSONparse(oo.extra).from}}</span></p>
<div v-if="shown.q" v-html="normalizeq(oo.q,{ret2:Noptions_ret2})" :style="{fontSize:'12pt',fontFamily:'Cambria'}" ></div>
<div v-if="shown.q" :style="{display:'block',height:(oo._extb_height||0)+'px'}"></div>
<div v-if="shown.a&&!displayADirectly"><img :src='API.host+"/oss-storage/"+oo.a.replace("<answerparser>","").replace("</answerparser>","").split("|")[0]+".png"'/></div>
<div v-if="shown.p&&!displayADirectly"><img :src='API.host+"/oss-storage/"+oo.a.replace("<answerparser>","").replace("</answerparser>","").split("|")[1]+".png"'/></div>
<div v-if="displayADirectly">

         <n-image v-if="shown.a||showTL[oo.id]" lazy :src="(XKWGetFile[oo.id]||{a:''}).a" :width="700"><template #placeholder><n-spin/></template></n-image>
         <n-image  v-if="shown.a||showTL[oo.id]" lazy :src="(XKWGetFile[oo.id]||{p:''}).p" :width="700"><template #placeholder><n-spin/></template></n-image>

        <div>
    </div></div>
<n-button text @click="markAsDone(oo)">标记为已完成</n-button>
<n-text>完成状态：{{doneinfo[oo.id]}}</n-text>
<n-button @click="showTL[oo.id]=true">显示本题答案</n-button>

</div>
</div>          </n-image-group></div>

</template>

<script setup>

import { onMounted, ref } from "vue"
import {useRoute,useRouter} from "vue-router"
const route=useRoute(),router=useRouter()

import {NButton,NCheckbox,NP,NSpin,NImage,NImageGroup,NText} from "naive-ui"

import {normalizeq} from "../../shared/nomorlize_q"
import {qtypes} from "../../shared/define_basic_qtypes"
import { API } from "../../shared/APIHelper"
import swal from "sweetalert"
const shown=ref({
    q:true,
    a:false,
    p:false
})

const showTL=ref({})

const Noptions_ret2=ref(false)
const grouptitle=ref("")

const Tlist=ref({})
let groupentry=[]
API.post("/api/group/get",{id:route.params.id}).then(sss=>{

sss.entry.split(",").forEach(v => {
    Tlist.value[v]=qtypes
});

groupentry=sss.entry.split(",")



grouptitle.value=sss.title

Promise.all(sss.entry.split(",").map(v=>new Promise((res,rej)=>{
API.get("/api/qapi/get/"+v).then(i=>{
    Tlist.value[v]=i
})
GetDoneInfo(v)
}))).then(()=>{

})
// fetch("/api/get",{"method":"POST","body":JSON.stringify({id:v}),"headers":{"Content-Type":"application/json"}}).then(o=>o.json()).then(i=>{
//     Tlist.value[v]=i
// })
// }))).then(()=>{

// })



})




//adddddd


const _JSONparse=(v)=>{return JSON.parse(v)}

const doneinfo=ref({})

,chunk2array=mm=>Object.entries(mm).map(o=>o[1])


const markAsDone=async(rel)=>{
    console.log(rel);
    await API.post("/api/qapi/doneinfo/mark",{
quuid:rel.id,
timestamp:(new Date()).getTime(),
displayednote:"",
note :"",
rate:50,
bankid:rel.bankid

    })
}

const markAsDoneAll=async()=>{
        Promise.all(Object.entries(Tlist.value).map(rr=>markAsDone(rr[1]))).then(v=>{
            swal("ok.")
        })
}

const GetDoneInfo=async(id)=>{
    doneinfo.value[id]= await API.get("/api/qapi/doneinfo/getbyquuid/"+id)
}


const displayADirectly=ref(false),XKWGetFile=ref({})
const handledisplayADirectlyCheckedChange=(checked)=>{
    console.log(checked);
displayADirectly.value=checked
if(displayADirectly.value){
    Object.entries(Tlist.value).forEach(v1 => {
        console.log(v1);
            API.get("/api/xkw-helper/get_more_detail/600/"+v1[1].bankid+"/"+v1[1].qid).then(r=>{
                
        XKWGetFile.value[v1[1].id]={
            a:API.host+"/api/xkw-helper/route-pic?purl="+btoa(r.data.answerImg.replace("@2","@3").replace("c2","c1")),
            p:API.host+"/api/xkw-helper/route-pic?purl="+btoa(r.data.parseImg.replace("@2","@3").replace("c2","c1")),
        }
})
    });
}
}
</script>

<style>
@media print{
    .noprint{
        display: none;
    }

}

.noprint{
    user-select: none;
}

/* .labi-container{
    display: block;
    height: fit-content;
    width: 100%;
    position: absolute;
    z-index: -1;
}
.labi-block{
    display: block;
    width: 100%;
    border-bottom-color: black;
    border-bottom-width: 2px;
    position:relative;
    border-bottom-style: dotted;
    text-align:right;
} */



td{
    padding:0
}
</style>
<style scoped>
img{
    max-width: 700px;
}
</style>