<template>
    <n-button class="noprint" @click="shown.q=!shown.q">Q</n-button>
    <n-button class="noprint" @click="shown.a=!shown.a">A</n-button>
    <n-button class="noprint" @click="shown.p=!shown.p">P</n-button>
    <n-button class="noprint" @click="currentClicker=addExtBlank">单击题面时增加空格</n-button>
    <n-button class="noprint" @click="fontreset">字体转为Times</n-button>
    <n-button class="noprint" @click="printhelper_columns==2?(printhelper_columns=1):(printhelper_columns=2)">改变列数
    </n-button>
    <n-button class="noprint" @click="currentClicker=()=>{};optiontableInit()">修正opttable</n-button>
    <n-button class="noprint" @click="Noptions_ret2=true">Retheme 2</n-button>
    <n-button class="noprint" @click="titleformat++">Title format</n-button>
    <n-button class="noprint" @click="infoformat++">Info format</n-button>
    <n-button class="noprint" @click="op2change()">进入不包含fixed content的修正页面</n-button>
    <div :style="{width:'18.76cm','line-height':'normal'}" id="oonom">
        <div class="noprint">
            <div class="labi-container">
                <div class="labi-block" v-for="rr in [1,2,3,4,5,6,7]" :key="rr" :style="{height:1045+'px'}">Page #
                    {{rr}}</div>
            </div>
        </div>
        <div id="corehtml" :style="{width:'18.76cm',columns:printhelper_columns,'line-height':'normal'}">

            <p v-if="titleformat%titleformatCount==0" style="font-size:6.5pt;font-family:Cambria , 仿宋;margin:0px">
                Generated by thost | Group UUID: {{$route.params.id}} | Title: {{grouptitle}}</p>
            <div v-if="titleformat%titleformatCount==1" style="text-align:center;font-family:Cambria , 仿宋;margin:0px">
                <p style="font-size:10pt;">{{grouptitle}}</p>
                <p style="font-size:6.5pt;">Generated by thost | UUID: <span
                        style="font-family:'courier new'">{{$route.params.id}}</span></p>
            </div>
            <div v-if="titleformat%titleformatCount==2" style="text-align:center;font-family:黑体;margin:0px">
                <p style="font-size:10pt;">{{grouptitle}}</p>
            </div>
            <div v-for="oo,i in chunk2array(Tlist)" :key="oo.id" @click="currentClicker(oo.id)"
                :data_type="_JSONparse(oo.extra).info[0]" class="___core_block" :data_id="i">

                <p v-if="infoformat%infoformatCount==0" style="font-size:6.5pt;margin:0px;font-family:Cambria , 仿宋;">
                    UUID:<span style="font-family:'courier new'">{{oo.id}}</span> | qid:<span
                        style="font-family:'courier new'">{{oo.qid}}</span> <span v-if="shown.q">| 
                        {{_JSONparse(oo.extra).info[0]}} | {{_JSONparse(oo.extra).info[1]}} | Origin: {{_JSONparse(oo.extra).from}}</span></p>
                <div v-if="infoformat%infoformatCount==0">
                    <div v-if="shown.q" v-html="normalizeq(oo.q,{ret2:Noptions_ret2,tindex:i+1,includeti:true})"
                        :style="{fontSize:'9.5pt',fontFamily:__Fontfamily}"></div>
                </div>
                <div v-if="infoformat%infoformatCount==1">
                    <div v-if="shown.q"
                        v-html="normalizeq(oo.q,{ret2:Noptions_ret2,tindex:i+1,gtittype:3,ootInfo:_JSONparse(oo.extra).info})"
                        :style="{fontSize:'9.5pt',fontFamily:__Fontfamily}"></div>
                </div>
                <div v-if="infoformat%infoformatCount==2">
                    <div v-if="shown.q"
                        v-html="normalizeq(oo.q,{ret2:Noptions_ret2,tindex:i+1,gtittype:4})"
                        :style="{fontSize:'9.5pt',fontFamily:__Fontfamily}"></div>
                </div>
                <div v-if="shown.q" :style="{display:'block',height:(oo._extb_height||0)+'px'}" class="extblank"></div>
                <div v-if="shown.a"><img
                        :src='API.host+"/oss-storage/"+oo.a.replace("<answerparser>","").replace("</answerparser>","").split("|")[0]+".png"' />
                </div>
                <div v-if="shown.p"><img
                        :src='API.host+"/oss-storage/"+oo.a.replace("<answerparser>","").replace("</answerparser>","").split("|")[1]+".png"' />
                </div>
            </div>
        </div>
    </div>

</template>

<script setup>
    import {
        onMounted,
        ref
    } from "vue"
    import {
        useRoute,
        useRouter
    } from "vue-router"
    const route = useRoute(),
        router = useRouter()

    import {
        NButton
    } from "naive-ui"

    import {
        normalizeq
    } from "../../shared/nomorlize_q"
    import {qtypes} from "../../shared/define_basic_qtypes"

    import {
        API
    } from "../../shared/APIHelper"
    const shown = ref({
        q: true,
        a: false,
        p: false
    })


    const titleformat = ref(0),
        infoformat = ref(0),
        titleformatCount = 3,
        infoformatCount = 3

    const grouptitle = ref("")

    const Tlist = ref({})
    const Noptions_ret2 = ref(false)
    API.post("/api/group/get", {
        id: route.params.id
    }).then(sss => {

        sss.entry.split(",").forEach(v => {
            Tlist.value[v] = qtypes
        });





        grouptitle.value = sss.title

        Promise.all(sss.entry.split(",").map(v => new Promise((res, rej) => {
            API.get("/api/qapi/get/" + v).then(i => {
                Tlist.value[v] = i
            })
        }))).then(() => {

        })
        // fetch("/api/get",{"method":"POST","body":JSON.stringify({id:v}),"headers":{"Content-Type":"application/json"}}).then(o=>o.json()).then(i=>{
        //     Tlist.value[v]=i
        // })
        // }))).then(()=>{

        // })



    })




    //adddddd


    const _JSONparse = (v) => {
            return JSON.parse(v)
        }

        ,
        chunk2array = mm => Object.entries(mm).map(o => o[1])


    const currentClicker = ref((v) => {})

    const addExtBlank = (id) => {
        Tlist.value[id]._extb_height = (Tlist.value[id]._extb_height || 0) + 50
        console.log(Tlist.value[id]._extb_height);
    }

    const printhelper_columns = ref(1)


    const op2change = () => {
        localStorage.setItem("___thost___html_export", document.getElementById("corehtml").outerHTML)
        router.push("/grouping/preexport-2/" + route.params.id)
    }

    const __Fontfamily = ref("Cambria , 宋体")
    const fontreset = () => {
        __Fontfamily.value = "Times New Roman , 宋体!important"
    }
    const optiontableInit = () => {
        document.querySelectorAll("table[name=optionsTable]").forEach(v => {
            if (v.querySelectorAll("td").length == 4) {
                console.log("oo", v);
                let opts = [],
                    lns = 1
                v.querySelectorAll("td").forEach(oo => {
                    opts.push(oo.outerHTML)
                })
                v.addEventListener("click", () => {
                    console.log("click");
                    const {
                        ctn,
                        next_lns
                    } = toTable(opts, lns)
                    v.innerHTML = ctn
                    lns = next_lns
                })
            }

        })

        function toTable(opts, lns) {
            if (lns == 1) {
                return {
                    ctn: "<tbody><tr>" + opts.join("") + "</tr></tbody>",
                    next_lns: 2
                }
            }
            if (lns == 2) {
                return {
                    ctn: `<tbody><tr>${opts[0]}${opts[1]}</tr><tr>${opts[2]}${opts[3]}</tr></tbody>`,
                    next_lns: 4
                }
            }
            if (lns == 4) {
                return {
                    ctn: "<tbody><tr>" + opts.join("</tr><tr>") + "</tr></tbody>",
                    next_lns: 1
                }
            }
        }


    }

    const HandleEnFormat = () => {

    }



    const _LOG = console.log
</script>

<style>
    @media print {
        .noprint {
            display: none;
        }

    }

    .labi-container {
        display: block;
        height: fit-content;
        width: 100%;
        position: absolute;
        z-index: -1;
    }

    .labi-block {
        display: block;
        width: 100%;
        border-bottom-color: black;
        border-bottom-width: 2px;
        position: relative;
        border-bottom-style: dotted;
        text-align: right;
    }

    /* img { */
        /* max-width: 350px; */
    /* } */

    td {
        padding: 0
    }
</style>