export default [
    {path:"/zujuanink-v2",redirect:"/zujuanink/home"},
    {path:"/zujuanink-v2/home",component: ()=>import("./home.vue")},
    {path:"/zujuanink-v2/preparing-room",component: ()=>import("./preparingRoom.vue")},
    {path:"/zujuanink-v2/room",component: ()=>import("./room.vue")},
    {path:"/zujuanink-v2/room/checkout",component: ()=>import("./room.checkout.vue")},
    {path:"/zujuanink-v2/room-ild",component: ()=>import("./ild/room.vue")},
    {path:"/zujuanink-v2/room-ild/checkout",component: ()=>import("./ild/room.checkout.vue")},
    {path:"/zujuanink-v2/list/failedcoll",component: ()=>import("./list.failedcoll.vue")},
    {path:"/zujuanink-v2/records",component: ()=>import("./records.vue")},
    {path:"/zujuanink-v2/debugger/showImgFromDonerec/:id",component: ()=>import("./debugger/debugger.showImgFromDonerec.vue")},
    {path:"/zujuanink-v2/debugger/generateImg",component: ()=>import("./debugger/debugger.generateImg.vue")},
    {path:"/zujuanink-v2/room-dev",component: ()=>import("./room/roomHost.vue")},
    {path:"/zujuanink-v2/preparing-room/paper",component: ()=>import("./APIList/paper.vue")},
]