<template>
<div v-if="step==1">
    <p>标题：</p>
    <n-input v-model:value="GPtitle"></n-input>
    <p>Group uuid：</p>
    <n-input v-model:value="GPUUID"></n-input>
<p>标题形式：</p>
<p>1:</p>
<div class="bordered">
    <p style="font-size:6.5pt;font-family:'Times New Roman' , 仿宋;margin:0px">
                Generated by thost | Group UUID: {{GPUUID}} | Title: {{GPtitle}}</p>
</div>
<p>2:</p>
<div class="bordered">
<div  style="text-align:center;font-family:Cambria , 仿宋;margin:0px">
                <p style="font-size:10pt;">{{GPtitle}}</p>
                <p style="font-size:6.5pt;">Generated by thost | UUID: <span
                        style="font-family:'courier new'">{{GPUUID}}</span></p>
            </div>
        </div>


        <p>3:</p>
        <div class="bordered">

            <div style="text-align:center;font-family:黑体;margin:0px">
                <p style="font-size:10pt;">{{GPtitle}}</p>
            </div>
        </div>

        <n-input-number v-model:value="GTitleFormat"></n-input-number>
<p>正文信息：1，完整；2.题型+难度；3.仅含题号</p>
<n-input-number v-model:value="GContentFormat"></n-input-number>


<n-button @click="step=2;initGQPContent()">NEXT</n-button>
</div>

<div v-show="step==2">

<div id="_GQP_content_core"  :style="{width:'18.76cm',columns:1,'line-height':'normal'}">

</div>

</div>
</template>
<script setup>

import {ref,nextTick} from "vue"
import {NInput,NInputNumber,NButton} from "naive-ui"


import { useRouter,useRoute } from "vue-router";
const router=useRouter(),route=useRoute()
const step=ref(1)

const GPtitle=ref(""),GPUUID=ref(""),GTitleFormat=ref(1),GContentFormat=ref(1)

import { normalizeqA } from "./nomorlize_q"

const initGQPContent=async()=>{
    let htmlelem=document.createElement("div")
    let ctncode=""
        ctncode+=`    <p style="font-size:6.5pt;font-family:'Times New Roman' , 仿宋;margin:0px">
                Generated by thost | Title: ${GPtitle.value}</p>`
                ctncode+="<div>"
    for (let i = 0; i < window.TList.length; i++) {
        const qcontent=window.TList[i]
            ctncode+=`
            <div class="qqmain" id="qmain-${i}">
            <div class="qblock" id="qblock-${i}">${normalizeqA(qcontent.body,{GContentFormat,qcontent,index:i+1})}
            
            <div class="extb" id="extb-${i}"></div>    </div>

            
            </div>
            `
    }
    ctncode+="</div>"
    document.getElementById("_GQP_content_core").innerHTML=ctncode
    function toTable(opts,lns){
    if(lns==1){
        return "<tbody><tr>"+opts.join("")+"</tr></tbody>"
    }
    if(lns==2){
        return `<tbody><tr>${opts[0]}${opts[1]}</tr><tr>${opts[2]}${opts[3]}</tr></tbody>`
    }
    if(lns==4){
        return "<tbody><tr>"+opts.join("</tr><tr>")+"</tr></tbody>"
    }
}
await nextTick()
    document.getElementById("_GQP_content_core").querySelectorAll("table[name=optionsTable]").forEach(v=>{
        let ops=[],maxw=0
        v.querySelectorAll("td").forEach(oo=>{
                maxw=Math.max(maxw,oo.querySelector("span").clientWidth)
                ops.push(oo.outerHTML)
            })
            console.log(maxw);
        if(maxw>=v.clientWidth/2){

        }else if(maxw>=v.clientWidth/4){
            v.innerHTML=toTable(ops,2)
            console.log(2);
        }else{
            v.innerHTML=toTable(ops,1)
            console.log(4);
        }
        // console.log(v.innerHTML);
        
    })

    window.HTMLExportString=document.getElementById("_GQP_content_core").innerHTML
    router.push("/gen/"+GPUUID.value)
    return "Inited."
}
</script>


<style>
.bordered{
border: 1px dashed red;
}
</style>