<template>
 <div
        style="text-align: center; font-family: Cambria, 仿宋; margin: 0px"
      >
        <p style="font-size: 10pt">{{ $attrs.data.title }}</p>
        <p style="font-size: 6.5pt">
          Generated by thost | UUID:
          <span style="font-family: 'courier new'">{{ $attrs.data.guid }}</span>
        </p>
      </div>
</template>
<script setup>

</script>