<template>
      <p
        style="font-size: 6.5pt; font-family: Cambria, 仿宋; margin: 0px"
      >
        Generated by thost | Group UUID:
        <span style="font-family: 'courier new'">{{ $attrs.data.guid }}</span> |
        Title: {{ $attrs.data.title }}
      </p>
</template>
<script setup>

</script>